# Reference: https://github.com/i3/i3/blob/next/etc/config

# I try to only use one app per workspace, so I think this tree normalization
# stuff can be disabled.
#
# https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
alt-0 = 'workspace 0'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'

alt-shift-0 = 'move-node-to-workspace 0'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'

# Prevent accidental hiding
cmd-h = []
cmd-m = []

[gaps]
inner.horizontal = [{ monitor."dell" = 10 }, 0]
outer.left = [{ monitor."dell" = 500 }, 0]
outer.right = [{ monitor."dell" = 500 }, 0]

[workspace-to-monitor-force-assignment]
5 = 'built-in' # Zoom

# Slack
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['move-node-to-workspace 0']

# Kitty
[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = ['move-node-to-workspace 1']

# Chrome
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = ['move-node-to-workspace 2']

# VSCode
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['move-node-to-workspace 4']

# Zoom
[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = ['move-node-to-workspace 5']
